export enum AnalyticsEvents {
  EXTENSION_INSTALLED = 'extensionInstalled',
  EXTENSION_ACTIVATED = 'extensionActivated',
  TRANSLATE_TEXT = 'translateText',
  ANALYZE_DE_TEXT = 'analyzeDeText',
  OPEN_SETTINGS = 'openSettings',
  CHANGE_TARGET_LANGUAGE = 'changeTargetLanguage',
  CHANGE_FULL_TEXT_TRANSLATION_ENABLED = 'changeFullTextTranslationEnabled',
  OPEN_DICTIONARY = 'openDictionary',
  ADD_TO_DICTIONARY = 'addToDictionary',
  DELETE_FROM_DICTIONARY = 'deleteFromDictionary',
  STUDY_WORDS = 'studyWords',
  STUDY_WORDS_EASY = 'studyWordsEasy',
  STUDY_WORDS_MEDIUM = 'studyWordsMedium',
  STUDY_WORDS_HARD = 'studyWordsHard',
  STUDY_WORDS_FLIP_FLASHCARD = 'studyWordsFlipFlashcard',
  STUDY_WORDS_SESSION_FINISHED = 'studyWordsSessionFinished',
  STUDY_WORDS_SESSION_ABORTED = 'studyWordsSessionAborted',
  STUDY_WORDS_TOGGLE_USAGE_EXAMPLES = 'studyWordsToggleUsageExamples',
}
